return {
  "onsails/lspkind.nvim",
  opts = {
  mode = "symbol",
  symbol_map = {
    NONE = "",
    Array = "",
    Boolean = "",
    Class = "",
    Key = "",
    Namespace = "",
    Null = "",
    Number = "#",
    Object = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",--
    String = "",
    TypeParameter = "",
    Unit = "",
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "󰜢",
    Variable = "",
    Interface = "",
    Module = "",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Color = "󰏘",
    File = "󰈙",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
  },
}
}
